/*
 * main.c
 *
 * Runs a small quantized CNN directly on the MSP-EXP430F5529LP
 * LaunchPad for parking-spot occupancy classification.
 *
 * IMPORTANT: this performs real convolutions. CONV1_W / CONV2_W are
 * 3x3 kernels that get SLID across the input feature map -- the same
 * 9 (or 9*in_ch) weights are reused at every output position. That
 * weight sharing + sliding window is what makes this a CNN and not a
 * precomputed lookup: the MSP430 recomputes every multiply-accumulate
 * itself, for whatever new BOARD_IMAGE ends up in model_weights.h.
 * Nothing about the class decision is baked in ahead of time -- only
 * the trained, quantized WEIGHTS are baked in (which is exactly how
 * every quantized embedded CNN, e.g. TFLite Micro, ships weights).
 *
 * Model (matches train_model.py / quantize_and_export.py):
 *
 *   BOARD_IMAGE (16x16x1, int8)
 *     -> Conv2D(4 filters, 3x3, valid)      -> 14x14x4
 *     -> ReLU + requantize to int8
 *     -> MaxPool2D(2x2)                     -> 7x7x4
 *     -> Conv2D(8 filters, 3x3, valid)      -> 5x5x8
 *     -> ReLU + requantize to int8
 *     -> MaxPool2D(2x2)                     -> 2x2x8
 *     -> Flatten (row-major h,w,c, matches Keras Flatten())  -> 32
 *     -> Dense(16) + ReLU + requantize to int8
 *     -> Dense(2)                            -> argmax -> VACANT/OCCUPIED
 *
 * MEMORY / DATAFLOW NOTE (referencing the memory-aware IoT paper
 * supplied for this project -- Banerjee et al., "Memory-aware
 * Efficient Deep Learning Mechanism for IoT Devices", ASAP 2021):
 *
 * The paper proposes four SRAM/Flash dataflow strategies for CNNs on
 * memory-constrained MCUs -- Percentage (Perc), One-at-a-Time (OaaT),
 * Move-the-Minimum (MM), and a Hybrid of OaaT+MM -- because their
 * target CNNs (MNIST/HAR/TrafficSign, Table II) need up to 80 KB of
 * SRAM to hold full feature maps and weights at once, more than the
 * MSP430F5529's 8 KB SRAM (paper Sec. II-A, Table III), which forces
 * them to stream/tile data between Flash and SRAM.
 *
 * This project's CNN is deliberately much smaller: every feature map
 * below is <=784 bytes and total weights are <1 KB, so ALL buffers
 * for the whole forward pass fit in SRAM simultaneously (worst case
 * is well under 5 KB, see the size comments on each array below).
 * That means we can use full materialization of every layer's
 * input/output in one pass with no Flash write-backs mid-inference --
 * which is exactly the paper's "One at a Time" (OaaT) dataflow
 * (Sec. IV-B), the option the paper's own results identify as the
 * most energy- and time-efficient of the four (Sec. V-B, Table IV),
 * used here because -- unlike the paper's benchmark CNNs -- our
 * model's own OaaT memory requirement already fits under the
 * MSP430's SRAM budget, so the paper's more complex tiled variants
 * (Perc / MM / Hybrid) are not needed here. If a future revision of
 * this project uses a bigger CNN that no longer fits, that is the
 * point at which the paper's MM or Hybrid dataflow should be
 * implemented instead of OaaT.
 *
 * Board pins used (confirmed against the F5529 LaunchPad pinout):
 *   P1.0 = LED1 (red)   -> lit for VACANT
 *   P4.7 = LED2 (green) -> lit for OCCUPIED
 *   P4.4 = UCA1 TXD, P4.5 = UCA1 RXD -> routed through the onboard
 *          eZ-FET to appear as a COM port on your computer
 */

#include <msp430.h>
#include <stdint.h>
#include "model_weights.h"

/* ------------------------------------------------------------
 * Fixed-point requantization: acc (int32) -> int8, using the
 * integer multiplier/shift pair generated by quantize_and_export.py.
 * See that script's header comment for the derivation. Rounding is
 * round-half-up; result is clamped to the int8 range used throughout
 * this model (-127..127, symmetric quantization, no zero-point).
 * ------------------------------------------------------------ */
static int8_t requantize(int32_t acc, int32_t mult, int shift) {
    int64_t val = (int64_t)acc * (int64_t)mult;
    int64_t rounded = val + ((int64_t)1 << (shift - 1));
    int32_t out = (int32_t)(rounded >> shift);
    if (out > 127)  out = 127;
    if (out < -127) out = -127;
    return (int8_t)out;
}

static int32_t relu32(int32_t v) {
    return (v < 0) ? 0 : v;
}

/* ------------------------------------------------------------
 * Layer buffers. Sizes annotated so the SRAM budget is auditable
 * against the MSP430F5529's 8 KB SRAM (see file header comment).
 * ------------------------------------------------------------ */
static int8_t  conv1_act[14][14][4];   /* 784 B  */
static int8_t  pool1[7][7][4];         /* 196 B  */
static int8_t  conv2_act[5][5][8];     /* 200 B  */
static int8_t  pool2[2][2][8];         /*  32 B  */
static int8_t  fc1_act[16];            /*  16 B  */
static int32_t fc2_out[2];             /*   8 B  */
/* Total resident activation storage: ~1.24 KB, comfortably under
 * the 8 KB SRAM budget even with UART/stack overhead. */

/* ------------------------------------------------------------
 * Layer 1: Conv2D(4 filters, 3x3, valid) on BOARD_IMAGE (16x16x1)
 * -> 14x14x4, ReLU, requantize.
 * ------------------------------------------------------------ */
static void conv1_layer(void) {
    int oc, oy, ox, ky, kx;
    for (oc = 0; oc < 4; oc++) {
        for (oy = 0; oy < 14; oy++) {
            for (ox = 0; ox < 14; ox++) {
                int32_t acc = CONV1_B[oc];
                for (ky = 0; ky < 3; ky++) {
                    for (kx = 0; kx < 3; kx++) {
                        acc += (int32_t)BOARD_IMAGE[oy + ky][ox + kx] *
                               (int32_t)CONV1_W[oc][0][ky][kx];
                    }
                }
                acc = relu32(acc);
                conv1_act[oy][ox][oc] =
                    requantize(acc, CONV1_REQUANT_MULT, CONV1_REQUANT_SHIFT);
            }
        }
    }
}

/* MaxPool2D(2x2) on conv1_act (14x14x4) -> pool1 (7x7x4) */
static void pool1_layer(void) {
    int c, y, x;
    for (y = 0; y < 7; y++) {
        for (x = 0; x < 7; x++) {
            for (c = 0; c < 4; c++) {
                int8_t a = conv1_act[2 * y][2 * x][c];
                int8_t b = conv1_act[2 * y][2 * x + 1][c];
                int8_t d = conv1_act[2 * y + 1][2 * x][c];
                int8_t e = conv1_act[2 * y + 1][2 * x + 1][c];
                int8_t m = a;
                if (b > m) m = b;
                if (d > m) m = d;
                if (e > m) m = e;
                pool1[y][x][c] = m;
            }
        }
    }
}

/* ------------------------------------------------------------
 * Layer 2: Conv2D(8 filters, 3x3, valid) on pool1 (7x7x4)
 * -> 5x5x8, ReLU, requantize.
 * ------------------------------------------------------------ */
static void conv2_layer(void) {
    int oc, oy, ox, ic, ky, kx;
    for (oc = 0; oc < 8; oc++) {
        for (oy = 0; oy < 5; oy++) {
            for (ox = 0; ox < 5; ox++) {
                int32_t acc = CONV2_B[oc];
                for (ic = 0; ic < 4; ic++) {
                    for (ky = 0; ky < 3; ky++) {
                        for (kx = 0; kx < 3; kx++) {
                            acc += (int32_t)pool1[oy + ky][ox + kx][ic] *
                                   (int32_t)CONV2_W[oc][ic][ky][kx];
                        }
                    }
                }
                acc = relu32(acc);
                conv2_act[oy][ox][oc] =
                    requantize(acc, CONV2_REQUANT_MULT, CONV2_REQUANT_SHIFT);
            }
        }
    }
}

/* MaxPool2D(2x2), valid, on conv2_act (5x5x8) -> pool2 (2x2x8).
 * (5 is odd, so -- matching Keras' default 'valid' pooling -- the
 * last row/column of the 5x5 map is dropped, exactly like Keras.) */
static void pool2_layer(void) {
    int c, y, x;
    for (y = 0; y < 2; y++) {
        for (x = 0; x < 2; x++) {
            for (c = 0; c < 8; c++) {
                int8_t a = conv2_act[2 * y][2 * x][c];
                int8_t b = conv2_act[2 * y][2 * x + 1][c];
                int8_t d = conv2_act[2 * y + 1][2 * x][c];
                int8_t e = conv2_act[2 * y + 1][2 * x + 1][c];
                int8_t m = a;
                if (b > m) m = b;
                if (d > m) m = d;
                if (e > m) m = e;
                pool2[y][x][c] = m;
            }
        }
    }
}

/* ------------------------------------------------------------
 * Layer 3: Dense(16), ReLU, requantize.
 * Input is pool2 flattened in (h, w, c) order -- the same order
 * Keras' Flatten() produces for a channels-last tensor -- so
 * FC1_W's 32 input columns line up with this exact iteration order.
 * ------------------------------------------------------------ */
static void fc1_layer(void) {
    int8_t flat[32];
    int idx = 0, y, x, c, o, i;
    for (y = 0; y < 2; y++)
        for (x = 0; x < 2; x++)
            for (c = 0; c < 8; c++)
                flat[idx++] = pool2[y][x][c];

    for (o = 0; o < 16; o++) {
        int32_t acc = FC1_B[o];
        for (i = 0; i < 32; i++) {
            acc += (int32_t)flat[i] * (int32_t)FC1_W[o][i];
        }
        acc = relu32(acc);
        fc1_act[o] = requantize(acc, FC1_REQUANT_MULT, FC1_REQUANT_SHIFT);
    }
}

/* ------------------------------------------------------------
 * Layer 4: Dense(2). No requantization needed -- both outputs share
 * the same accumulator scale, so comparing them directly (argmax)
 * is valid without converting back to a real probability. Softmax
 * is monotonic, so this decision is identical to comparing the
 * trained model's softmax outputs (see project notes, Sec. 17).
 * ------------------------------------------------------------ */
static int fc2_layer(void) {
    int o, i;
    for (o = 0; o < 2; o++) {
        int32_t acc = FC2_B[o];
        for (i = 0; i < 16; i++) {
            acc += (int32_t)fc1_act[i] * (int32_t)FC2_W[o][i];
        }
        fc2_out[o] = acc;
    }
    return (fc2_out[1] > fc2_out[0]) ? 1 : 0;   /* 1 = OCCUPIED, 0 = VACANT */
}

static int run_inference(void) {
    conv1_layer();
    pool1_layer();
    conv2_layer();
    pool2_layer();
    fc1_layer();
    return fc2_layer();
}

/* ------------------------------------------------------------
 * UART / LEDs (unchanged from the original firmware)
 * ------------------------------------------------------------ */
static void uart_init(void) {
    P4SEL |= BIT4 + BIT5;      /* P4.4 = UCA1TXD, P4.5 = UCA1RXD */
    UCA1CTL1 |= UCSWRST;
    UCA1CTL1 |= UCSSEL_2;      /* SMCLK */
    UCA1BR0 = 109;             /* ~9600 baud at ~1MHz SMCLK */
    UCA1BR1 = 0;
    UCA1MCTL = UCBRS_2;
    UCA1CTL1 &= ~UCSWRST;
}

static void uart_print(const char *s) {
    while (*s) {
        while (!(UCA1IFG & UCTXIFG)) { /* wait for TX buffer ready */ }
        UCA1TXBUF = *s++;
    }
}

int main(void) {
    WDTCTL = WDTPW + WDTHOLD;  /* stop watchdog timer */

    P1DIR |= BIT0;             /* LED1 (red)   = P1.0 = vacant indicator   */
    P4DIR |= BIT7;             /* LED2 (green) = P4.7 = occupied indicator */

    uart_init();

    int result = run_inference();

    if (result == 1) {
        P4OUT |= BIT7;
        P1OUT &= ~BIT0;
        uart_print("Spot status: OCCUPIED\r\n");
    } else {
        P1OUT |= BIT0;
        P4OUT &= ~BIT7;
        uart_print("Spot status: VACANT\r\n");
    }

    while (1) {
        __no_operation();
    }
}
